### PR TITLE
Inform the user about failures when reading thunks

### LINKED ISSUE #41: Show more informative message on UnrecognizedThunk
I encountered a situation where `nix-thunk update` (and also `ob thunk update`) failed with this error.  The problem ended up being that my editor had a swap file in the directory that was causing the UnrecognizedThunk error.  The ideal user experience would be to make it tolerate those situations, but if you don't want to do that, a more informative error message would help a LOT.

### PR DESCRIPTION
**Pull request by plt-amy**
When we can commit to a thunk specification, we print an informative
error message. When we didn't manage to find a specification at all, we
print a generic message and tell the user to run with verbosity to get
the errors for each spec.

Fixes #41

### CODE REVIEW

File: src/Nix/Thunk/Internal.hs [hunk 1]
```diff
@@ -520,7 +567,7 @@ updateThunkToLatest (ThunkUpdateConfig mBranch thunkConfig) target = do
     case mBranch of
       Nothing -> do
         (overwrite, ptr) <- readThunk target >>= \case
-          Left err -> failWith [i|Thunk update: ${err}|]
+          Left err -> failWith ("Thunk update failed: " <> prettyReadThunkError err)
```
Comment (madeline-os) [inline src/Nix/Thunk/Internal.hs:570]: Can we reduce the code duplication in these `failWith` calls?

**Review by madeline-os — CHANGES_REQUESTED** [review]
Looks good, except there is a bunch of duplication of logic for finally tidying up the error and displaying it to the user. I think we can dedupe that logic some before merging.

**Review by madeline-os — APPROVED** [review]
